spring.application.name=RetroReads
server.port = 8080

# spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:teste
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true 
#spring.h2.console.path=/h2-console
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.url=jdbc:mysql://localhost:3306/RetroReads
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
