package com.cruzeirodosul.RetroReads.config;

import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

import com.cruzeirodosul.RetroReads.models.Livro;
import com.cruzeirodosul.RetroReads.models.UserRetro;
import com.cruzeirodosul.RetroReads.repositories.LivroRepository;
import com.cruzeirodosul.RetroReads.repositories.UserRepository;

@Configuration
public class DataSeed implements CommandLineRunner {

	@Autowired
	UserRepository userRepository;
	
	@Autowired
	LivroRepository livroRepository;
	
	@Autowired
	PasswordEncoder passwordEncoder;

	@Override
	public void run(String... args) throws Exception {
		/*
		UserRetro u1 = new UserRetro(1l, 1, "lucas", "cruzeirod", "lucas@gmail.com", "70707070", passwordEncoder.encode("123"));
		userRepository.save(u1);
		
		Livro l1 = new Livro(null, "Mindset: A Nova Psicologia do Sucesso", 2017, "Português", "Brasil", 312, "Capa Comum", "Carol S. Dweck, ph.D., professora de psicologia na Universidade Stanford e especialista internacional em sucesso e motivação, desenvolveu, ao longo de décadas de pesquisa, um conceito fundamental: a atitude mental com que encaramos a vida, que ela chama de “mindset”, é crucial para o sucesso. Dweck revela de forma brilhante como o sucesso pode ser alcançado pela maneira como lidamos com nossos objetivos. O mindset não é um mero traço de personalidade, é a explicação de por que somos otimistas ou pessimistas, bem-sucedidos ou não. Ele define nossa relação com o trabalho e com as pessoas e a maneira como educamos nossos filhos. É um fator decisivo para que todo o nosso potencial seja explorado.", u1, "Carol S. Dweck", "Negócios e Carreira", 35.00f, "Objetiva", "23 x 16 x 1.8 cm");
		
		Livro l2 = new Livro(null, "O Homem Mais Rico da Babilônia", 2017, "Português", "Brasil", 160, "Capa Comum", "Baseando-se nos segredos de sucesso dos antigos babilônicos ― os habitantes da cidade mais rica e próspera de seu tempo ―, George S. Clason mostra soluções ao mesmo tempo sábias e muito atuais para evitar a falta de dinheiro, como não desperdiçar recursos durante tempos de opulência, buscar conhecimento e informação em vez de apenas lucro, assegurar uma renda para o futuro, manter a pontualidade no pagamento de dívidas e, sobretudo, cultivar as próprias aptidões, tornando-se cada vez mais habilidoso e consciente.", u1, "George S. Clason", "Negócios e Carreira", 15.00f, "HarperCollins", "20.6 x 13.4 x 0.6 cm");
		
		Livro l3 = new Livro(null, "Quebrando o Hábito de Ser Você Mesmo", 2018, "Português", "Brasil", 352, "Capa Comum", "Está emergindo uma nova ciência que habilita todos os seres humanos a criarem a realidade que preferirem. Neste livro, o renomado autor, palestrante, pesquisador e quiroprático Dr. Joe Dispenza combina os campos da física quântica, neurociência, química cerebral, biologia e genética para mostrar o que é realmente possível. \nNão só você vai ter o conhecimento necessário para alterar qualquer aspecto de si mesmo, mas também receberá as ferramentas, passo a passo, para aplicar o que aprendeu, de modo a promover as mudanças necessárias em qualquer área de sua vida. O Dr. Joe desmistifica os estudos antigos e preenche a lacuna entre a ciência e a espiritualidade. Através de suas eficazes oficinas e palestras, milhares de pessoas em 24 países diferentes têm utilizado esses princípios para mudar de dentro para fora. Quando você quebra o hábito de ser você mesmo e realmente muda sua mente, sua vida jamais será a mesma!", u1, "Dr. Joe Dispenza", "Autoajuda", 10.00f, "Citadel", "15.24 x 2.01 x 22.86");
		
		Livro l4 = new Livro(null, "Como Fazer Amigos e Influenciar Pessoa", 2019, "Português", "Brasil", 256, "Capa Comum", "Ao longo de oito décadas, este livro se tornou a referência quando o assunto é o desenvolvimento das relações humanas, das habilidades sociais e da comunicação eficiente. \nPartindo do princípio de que é preciso se interessar genuinamente por aqueles com quem interagimos, ele mudou a vida de milhões de pessoas, fazendo-as se sentirem mais seguras, abertas e confiantes em seus encontros sociais e profissionais. \nCom saborosas histórias, exemplos práticos e ótimos conselhos, esta é uma leitura prazerosa e fundamental para quem deseja criar bons vínculos, se tornar mais persuasivo, deixar uma marca positiva e inspirar os outros com energia e gentileza.", u1, "Dale Carnegie", "Autoajuda", 20.00f, "Editora Sextante", "22.6 x 15.8 x 1.8 cm");
		
		Livro l5 = new Livro(null, "O Diário de Anne Frank", 2020, "Português", "Brasil", 192, "Capa Comum", "O Diário de Anne Frank teve a autenticidade confirmada por peritos. Estudos forenses da caligrafia de Anne e exame do papel do diário, da tinta e da cola comprovaram ser de material existente na época. A conclusão foi oficialmente apresentada pelo Instituto Estatal Holandês para Documentação da Guerra.", u1, "Anne Frank", "Biografias", 15.00f, "Principis", "22.8 x 15.8 x 1.6 cm");
		
		Livro l6 = new Livro(null, "Box Sherlock Holmes - Obra Completa", 2019, "Português", "Brasil", 1808, "Capa Dura", "Em 1887, o escritor escocês Ssir Arthur Conan Doyle criou Sherlock Holmes, o infalível detetive a quem os agentes da Scotland Yard recorriam para solucionar os mistérios mais intrigantes da Inglaterra vitoriana. Desde então, as aventuras do mestre da investigação atraem leitores ávidos por chegar à última página e ver o enigma desvendado. \nPara desvendar mistérios, o faro e a astúcia de Sherlock Holmes levam às fontes menos óbvias, às informações mais precisas. Um modelo que influencia até hoje a literatura policial e revela fôlego para impressionar gerações de leitores através dos tempos. \nCada livro deste box de luxo contém...  \nVolume 1:  Um estudo em vermelho (romance) – 1887, O sinal dos quatro (romance) – 1890, As aventuras de Sherlock Holmes (contos) – 1892. Volume 2: Memórias de Sherlock Holmes (contos) – 1894, O cão dos Baskerville (romance) – 1902. Volume 3: A volta de Sherlock Holmes (contos) – 1905, O vale do medo (romance) – 1915. Volume 4: Os últimos casos de Sherlock Holmes (contos) – 1917, Histórias de Sherlock Holmes (contos) – 1927. ", u1, "Arthur Conan Doyle", "Biografias", 105.00f, "HarperCollins", "24.4 x 16.6 x 11.2 cm");
		
		Livro l7 = new Livro(null, "Entendendo Algoritmos: Um Guia Ilustrado Para Programadores e Outros Curiosos ", 2017, "Português", "Brasil", 264, "Capa Comum", "Um guia ilustrado para programadores e outros curiosos. Um algoritmo nada mais é do que um procedimento passo a passo para a resolução de um problema. Os algoritmos que você mais utilizará como um programador já foram descobertos, testados e provados. Se você quer entendê-los, mas se recusa a estudar páginas e mais páginas de provas, este é o livro certo. Este guia cativante e completamente ilustrado torna simples aprender como utilizar os principais algoritmos nos seus programas. \nO livro Entendendo Algoritmos apresenta uma abordagem agradável para esse tópico essencial da ciência da computação. Nele, você aprenderá como aplicar algoritmos comuns nos problemas de programação enfrentados diariamente. Você começará com tarefas básicas como a ordenação e a pesquisa. Com a prática, você enfrentará problemas mais complexos, como a compressão de dados e a inteligência artificial. Cada exemplo é apresentado em detalhes e inclui diagramas e códigos completos em Python. Ao final deste livro, você terá dominado algoritmos amplamente aplicáveis e saberá quando e onde utilizá-los. \nO que este livro inclui: a abordagem de algoritmos de pesquisa, ordenação e algoritmos gráficos; mais de 400 imagens com descrições detalhadas; comparações de desempenho entre algoritmos; exemplos de código em Python.", u1, "Aditya Bhargava", "Informática e Técnologia", 50.00f, "Novatec Editora", "23.4 x 17.2 x 1.4 cm");
		
		Livro l8 = new Livro(null, "Código Limpo: Habilidades Práticas do Agile Software ", 2009, "Português", "Brasil", 425, "Capa Comum", "Mesmo um código ruim pode funcionar. Mas se ele não for limpo, pode acabar com uma empresa de desenvolvimento. Perdem-se a cada ano horas incontáveis e recursos importantes devido a um código mal escrito. Mas não precisa ser assim. \nO renomado especialista em software, Robert C. Martin, apresenta um paradigma revolucionário com Código limpo: Habilidades Práticas do Agile Software. Martin se reuniu com seus colegas do Mentor Object para destilar suas melhores e mais ágeis práticas de limpar códigos “dinamicamente” em um livro que introduzirá gradualmente dentro de você os valores da habilidade de um profissional de softwares e lhe tornar um programador melhor –mas só se você praticar. \nQue tipo de trabalho você fará? Você lerá códigos aqui, muitos códigos. E você deverá descobrir o que está correto e errado nos códigos. E, o mais importante, você terá de reavaliar seus valores profissionais e seu comprometimento com o seu ofício. \nCódigo limpo está divido em três partes. Na primeira há diversos capítulos que descrevem os princípios, padrões e práticas para criar um código limpo. \nA segunda parte consiste em diversos casos de estudo de complexidade cada vez maior. Cada um é um exercício para limpar um código – transformar o código base que possui alguns problemas em um melhor e eficiente. A terceira parte é a compensação: um único capítulo com uma lista de heurísticas e “odores” reunidos durante a criação dos estudos de caso. O resultado será um conhecimento base que descreve a forma como pensamos quando criamos, lemos e limpamos um código.", u1, "Robert C. Martin", "Informática e Técnologia", 60.00f, "Alta Books", "16 x 2 x 23 cm");
		
		Livro l9 = new Livro(null, "A Revolução dos Bichos ", 2007, "Português", "Brasil", 152, "Capa Comum", "Escrita em plena Segunda Guerra Mundial e publicada em 1945 depois de ter sido rejeitada por várias editoras, essa pequena narrativa causou desconforto ao satirizar ferozmente a ditadura stalinista numa época em que os soviéticos ainda eram aliados do Ocidente na luta contra o eixo nazifascista. De fato, são claras as referências: o despótico Napoleão seria Stálin, o banido Bola-de-Neve seria Trotsky, e os eventos políticos - expurgos, instituição de um estado policial, deturpação tendenciosa da História - mimetizam os que estavam em curso na União Soviética. \nCom o acirramento da Guerra Fria, as mesmas razões que causaram constrangimento na época de sua publicação levaram A revolução dos bichos a ser amplamente usada pelo Ocidente nas décadas seguintes como arma ideológica contra o comunismo. O próprio Orwell, adepto do socialismo e inimigo de qualquer forma de manipulação política, sentiu-se incomodado com a utilização de sua fábula como panfleto. \nDepois das profundas transformações políticas que mudaram a fisionomia do planeta nas últimas décadas, a pequena obra-prima de Orwell pode ser vista sem o viés ideológico reducionista. Mais de sessenta anos depois de escrita, ela mantém o viço e o brilho de uma alegoria perene sobre as fraquezas humanas que levam à corrosão dos grandes projetos de revolução política. É irônico que o escritor, para fazer esse retrato cruel da humanidade, tenha recorrido aos animais como personagens. De certo modo, a inteligência política que humaniza seus bichos é a mesma que animaliza os homens. Escrito com perfeito domínio da narrativa, atenção às minúcias e extraordinária capacidade de criação de personagens e situações, A revolução dos bichos combina de maneira feliz duas ricas tradições literárias: a das fábulas morais, que remontam a Esopo, e a da sátira política, que teve talvez em Jonathan Swift seu representante máximo.", u1, "George Orwell", "Literatura e Ficção", 10.00f, "Companhia das Letras", "20.8 x 13.6 x 1.4 cm");
		
		Livro l10 = new Livro(null, "O Pequeno Príncipe ", 2018, "Português", "Brasil", 96, "Capa Comum", "Nesta história que marcou gerações de leitores em todo o mundo, um piloto cai com seu avião no deserto do Saara e encontra um pequeno príncipe, que o leva a uma aventura filosófica e poética através de planetas que encerram a solidão humana.\nUm livro para todos os públicos, O pequeno príncipe é uma obra atemporal, com metáforas pertinentes e aprendizados sobre afeto, sonhos, esperança e tudo aquilo que é invisível aos olhos.", u1, "Antonie de Saint-Exupéry", "Literatura e Ficção", 10.00f, "HarperCollins", "22.6 x 15 x 0.8 cm");
		
		Livro l11 = new Livro(null, "Carmilla - A Vampira de Karnstein +: O Vampiro, de John William Polidori ", 2023, "Português", "Brasil", 176, "Capa Dura", "Essa edição traz a primeira vampira da história e também a primeira história de vampiro já escrita em projeto gráfico especial, com curiosidades sobre as obras e os autores. Carmilla é uma obra precursora da temática de vampiros, considerada por muitos críticos como a melhor do século XIX, pela maneira como trabalha o suspense e o erotismo. Foi a partir dela que Drácula, de Bram Stoker, recebeu suas principais características. A vampira de Karnstein se torna o motivo dos horrores e depois do desejo profundo de Laura, uma jovem que vive somente na companhia do pai em um castelo isolado no Leste Europeu. O Vampiro, de John William Polidori, concretizou as lendas folclóricas sobre vampiro e deu a ele a cara que tem ainda hoje: um demônio aristocrata que ataca entre a alta sociedade.", u1, "Le Fanu J. Sheridan", "Fantasia, Horror e Ficção Científica", 25.00f, "Pandorga Editora", "14 x 2 x 21 cm");
		
		Livro l12 = new Livro(null, "Coleção Crônicas de Gelo e Fogo: 5 Volumes", 2022, "Português", "Brasil", 3512, "Capa Comum", "Kit As Cronicas de Gelo e Fogo: A Guerra dos Tronos ( Volume 1); A Fúria dos Reis ( Volume 2); A Tormenta de Espadas ( Volume 3 ); O Festim dos Corvos ( Volume 4 ); A Dança dos Dragões ( Volume 5 ).", u1, "George R.R. Martin", "Fantasia, Horror e Ficção Científica", 80.00f, "Suma das Letras", "45 x 35 x 20 cm");
		
		Livro l13 = new Livro(null, "Jantar Secreto", 2016, "Português", "Brasil", 368, "Capa Comum", "Um grupo de jovens deixa uma pequena cidade no Paraná para viver no Rio de Janeiro. Eles alugam um apartamento em Copacabana e fazem o possível para pagar a faculdade e manter vivos seus sonhos de sucesso na capital fluminense. Mas o dinheiro está curto e o aluguel está vencido. Para sair do buraco e manter o apartamento, os amigos adotam uma estratégia heterodoxa: arrecadar fundos por meio de jantares secretos, divulgados pela internet para uma clientela exclusiva da elite carioca. A partir daí, eles se envolvem em uma espiral de crimes, descobrem uma rede de contrabando de corpos, matadouros clandestinos e grã-finos excêntricos, e levam ao limite uma índole perversa que jamais imaginaram existir em cada um deles.", u1, "Raphael Montes", "Policial, Suspense e Mistério", 25.00f, "Companhia das Letras", "21 x 14 x 2.2 cm");
		
		Livro l14 = new Livro(null, "Coleção Agatha Christie", 2019, "Português", "Brasil", 640, "Capa Dura", "Livro 1 - Morte no Nilo\nLivro 2 - Um corpo na biblioteca\nLivro 3 - Assassinato no Expresso do Oriente \nA editora HarperCollins Brasil tem o orgulho de trazer aos leitores as melhores histórias de Agatha Christie, a eterna Dama do Crime. Aqui, corpos são encontrados em situações estranhas, tiros são dados no escuro e pessoas desaparecem sem deixar vestígios, mas definitivamente não há mistério sem solução. Criadora de algumas das maiores mentes analíticas da ficção policial (como Hercule Poirot, Miss Marple, Tommy e Tuppence, entre outros), Agatha Christie é, e sempre será, a inspiração máxima para todos os autores do gênero.  \nMorte no Nilo \nBela, rica e inteligente, a jovem herdeira Linnet Ridgeway parece conseguir tudo o que quer. No entanto, ao roubar o noivo de sua melhor amiga e se casa com ele sem pensar duas vezes, talvez Linnet esteja indo longe demais… Em sua viagem de lua de mel num cruzeiro pelo rio Nilo, no Egito, o casal apaixonado se depara com uma série de antagonistas interessados em sua fortuna e em provocar sua infelicidade. Então Linnet é encontrada morta, com um tiro na cabeça. O detetive Hercule Poirot, que por acaso também está no navio, entra em ação para tentar montar mais esse quebra-cabeça.   \nUm corpo na biblioteca \nO corpo de uma jovem é encontrado no tapete da biblioteca dos Bantry, às sete da manhã. A vítima é uma completa desconhecida, e o casal Bantry decide chamar as autoridades para investigar o caso ― e também, é claro, Miss Marple, detetive amadora e amiga da sra. Bantry. Tudo se complica ainda mais quando chega até eles a notícia de outra adolescente morta, carbonizada dentro de um carro incendiado em uma pedreira. Qual será a possível conexão entre os dois incidentes?  \nAssassinato no Expresso do Oriente \nNada menos que um telegrama aguarda Hercule Poirot na recepção do hotel em que se hospedaria, na Turquia, requisitando seu retorno imediato a Londres. O detetive belga, então, embarca às pressas no Expresso do Oriente, inesperadamente lotado para aquela época do ano. O trem expresso, porém, é detido a meio caminho da Iugoslávia por uma forte nevasca, e um passageiro com muitos inimigos é brutalmente assassinado durante a madrugada. Caberá a Poirot descobrir quem entre os passageiros seria capaz de tamanha atrocidade, antes que o criminoso volte a atacar ou escape de suas mãos.", u1, "Agatha Christie", "Policial, Suspense e Mistério", 50.00f, "HarperCollins", "22.2 x 14.6 x 4.8 cm");
		
		Livro l15 = new Livro(null, "Demon Slayer - Kimetsu no Yaiba Vol. 12", 2021, "Português", "Brasil", 192, "Capa Comum", "Pela primeira vez, em 113 anos, um jougen foi derrotado, e isso só causa tensão entre a alta cúpula dos doze Kizuki. Do lado dos humanos, Haganezuka está furioso com Tanjirou, que quebrou sua espada na luta contra Gyuutarou. Agora, nosso herói partirá em uma viagem para conseguir consertá-la.", u1, "Koyoharu Gotouge", "HQs, Mangásce Graphic Novels", 25.00f, "Panini", "19.81 x 13.46 x 1.52 cm");
		
		Livro l16 = new Livro(null, "O Alquimista", 2017, "Português", "Brasil", 208, "Capa Comum", "Combinando espiritualidade, sabedoria e misticismo, O alquimista é uma inspiradora e emocionante história de autodescoberta que vem transformando a vida de milhões de leitores ao redor do mundo há mais de trinta anos. \nSantiago, um jovem pastor da Andaluzia, parte rumo ao Egito em busca de um tesouro escondido entre as Pirâmides. O que ele não sabe é que sua jornada o levará a riquezas muito diferentes – e mais satisfatórias – do que ele estava esperando. Ao longo do caminho, uma cigana, um homem que se diz rei e um alquimista lhe indicam a direção em que deve seguir e o ajudam a perceber que o maior tesouro se encontra dentro dele mesmo. \nCom a prosa poética de Paulo Coelho, este romance encantador nos recorda da sabedoria de ouvir nossos corações, reconhecer as oportunidades da vida e, mais importante, sempre seguir nossos sonhos.", u1, "Paulo Coelho"," Poesia", 10.00f, "Paralela", "21 x 13.8 x 1.4 cm");
		
		Livro l17 = new Livro(null, "O Amor é um Cão dos Diabos - Livro de Bolso", 2010, "Português", "Brasil", 304, "Capa Comum", "Como a prosa, cada poema de Charles Bukowski corta como aço de navalha. Ele expõe as vísceras da realidade, revolve o cotidiano, e, de onde nem se pensa que sairá um poema, brotam versos de pura genialidade. Poucos souberam, como Charles Bukowski, arrancar versos de quartos sórdidos de hotel, becos imundos, mulheres de todas as formas, bocas vermelhas demais, madrugadas longas, solitárias. É o bepop dos marginalizados, dos perdedores, pensadores de sarjeta, filósofos encharcados de uísque vagabundo.", u1, "Charles Bukowski", "Poesia", 10.00f, "L&PM Editores", "17.6 x 10.8 x 1.2 cm");
		
		Livro l18 = new Livro(null, "Dom Casmurro", 2019, "Português", "Brasil", 208, "Capa Comum", "Em Dom Casmurro, o narrador Bento Santiago retoma a infância que passou na Rua de Matacavalos e conta a história do amor e das desventuras que viveu com Capitu, uma das personagens mais enigmáticas e intrigantes da literatura brasileira. Nas páginas deste romance, encontra-se a versão de um homem perturbado pelo ciúme, que revela aos poucos sua psicologia complexa e enreda o leitor em sua narrativa ambígua acerca do acontecimento ou não do adultério da mulher com olhos de ressaca, uma das maiores polêmicas da literatura brasileira.", u1, "Machado de Assis", "Literatura e Ficção", 15.00f, "Principis", "15.24 x 1.22 x 22.86 cm");

		Livro l19 = new Livro(null, "Apenas um Olhar", 2019, "Português", "Brasil", 352, "Capa Comum", "Ao buscar um filme que mandou revelar, Grace encontra, no meio das fotos, uma que não pertence ao rolo. É uma imagem de cinco pessoas, tirada no mínimo vinte anos atrás. Quatro delas não lhe são familiares, mas a quinta é muito parecida com seu marido, Jack. \nAo ver a foto, Jack nega ser ele. Só que, mais tarde, ele foge sem nenhuma explicação, levando a fotografia. \nSem saber por que ele se foi, Grace luta para proteger os filhos da ausência do pai. Cada dia que passa traz mais dúvidas sobre si mesma, sobre seu casamento e sobre Jack, assim como a compreensão de que há outras pessoas procurando por ele e pela fotografia – inclusive um violento e silencioso assassino. \nQuando entende que não pode contar com a polícia, e que seus vizinhos e amigos têm os próprios objetivos secretos, Grace precisa enfrentar as partes sombrias de seu passado para descobrir a verdade que pode trazer seu marido de volta.", u1, "Harlan Coben", "Policial, Suspense e Mistério", 28.00f, "Editora Arqueiro", "22.8 x 15.6 x 2 cm");

		Livro l20 = new Livro(null, "A Cinza das Horas", 2013, "Português", "Brasil", 144, "Capa Comum", "Obra de estreia de Manuel Bandeira, escrito no sanatório onde estava em tratamento, nos mostra um poeta que fala sobre as agruras da condição humana, as dores do amor e da morte, do desamparo e da solidão. É este estado de espírito, o “cinza” das horas do título desta belíssima obra, que é compartilhado carinhosamente com seus leitores.", u1, "Manuel Bandeira", "Poesia", 35.00f, "Global Editora", "22.8 x 13.2 x 1 cm");

		
		livroRepository.saveAll(Arrays.asList(l1,l2,l3,l4,l5,l6,l7,l8,l9,l10,l11,l12,l13,l14,l15,l16,l17,l18,l19,l20)); */
		
	}

}
